# Generated by Django 4.0.3 on 2022-03-31 01:09

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='CreditCardExpire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creditCardExpire', models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='Please enter mm/yy', regex='^(?:\\d{2}\\/\\d{2})$')])),
            ],
        ),
        migrations.CreateModel(
            name='CreditCardNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creditCardNumber', models.CharField(blank=True, max_length=16, null=True, validators=[django.core.validators.RegexValidator(message='Please enter with no spaces', regex='^(?:4[0-9]{12}(?:[0-9]{3})?|(?:5[1-5][0-9]{2}|222[1-9]|22[3-9][0-9]|2[3-6][0-9]{2}|27[01][0-9]|2720)[0-9]{12}|3[47][0-9]{13})$')])),
            ],
        ),
        migrations.CreateModel(
            name='CreditCardSecurity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creditCardSecurity', models.CharField(blank=True, max_length=3, null=True, validators=[django.core.validators.RegexValidator(message='CVV 3 digit code', regex='^(?:\\d{3})$')])),
            ],
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(blank=True, max_length=50, null=True, validators=[django.core.validators.RegexValidator(message='Emails are case-insensitive', regex='^[A-Z0-9._%+-]+@[A-Z0-9.-]+\\.[A-Z]{2,}$')])),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(blank=True, max_length=30, null=True)),
                ('lastName', models.CharField(blank=True, max_length=30, null=True)),
                ('userName', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('address', models.CharField(blank=True, max_length=75, null=True)),
                ('email', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shopping.email')),
            ],
        ),
        migrations.CreateModel(
            name='PhoneNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phoneNumber', models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message="Please enter as '+##########'", regex='^\\+?1?\\d{9,15}$')])),
            ],
        ),
        migrations.RenameField(
            model_name='product',
            old_name='title_text',
            new_name='name',
        ),
        migrations.CreateModel(
            name='Administrator',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shopping.person')),
                ('adminList', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopping.company')),
            ],
            bases=('shopping.person',),
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shopping.person')),
                ('medicalInfo', models.CharField(blank=True, max_length=500, null=True)),
                ('creditCardExpireDate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shopping.creditcardexpire')),
                ('creditCardNumber', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shopping.creditcardnumber')),
                ('creditCardSecurity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shopping.creditcardsecurity')),
            ],
            bases=('shopping.person',),
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.AddField(
            model_name='person',
            name='phoneNumber',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shopping.phonenumber'),
        ),
    ]
