# Generated by Django 4.0.3 on 2022-03-31 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0002_company_creditcardexpire_creditcardnumber_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='medicalInfo',
        ),
        migrations.RemoveField(
            model_name='person',
            name='firstName',
        ),
        migrations.RemoveField(
            model_name='person',
            name='lastName',
        ),
        migrations.AlterField(
            model_name='person',
            name='userName',
            field=models.CharField(max_length=30),
        ),
    ]
