# Generated by Django 4.0.3 on 2022-03-31 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0003_remove_customer_medicalinfo_remove_person_firstname_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='address',
        ),
    ]
